#!/usr/bin/env python3
"""
GPT Agent Orchestrator
======================

A standalone CLI tool that runs a queue of tasks through an AI coding
agent using a hook-driven chain. Tasks can be manual markdown files or
auto-generated by GPT.

Usage:
  Manual mode:  python orchestrator.py ~/projects/my-app
  GPT mode:     python orchestrator.py ~/projects/my-app --gpt -d "Build a REST API"

Tasks are placed in the tasks/ directory as numbered markdown files:
  tasks/1.md, tasks/2.md, tasks/3.md, ...
"""

import argparse
import json
import os
import signal
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# Resolve paths relative to this script
ORCHESTRATOR_DIR = Path(__file__).parent.resolve()
sys.path.insert(0, str(ORCHESTRATOR_DIR))

from state import State

# Only import GPT modules if needed (they require openai)
GPTPlanner = None


def lazy_import_gpt():
    global GPTPlanner
    if GPTPlanner is None:
        from gpt_planner import GPTPlanner as _GPTPlanner
        GPTPlanner = _GPTPlanner


# ──────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────


def parse_args():
    parser = argparse.ArgumentParser(
        description="GPT Agent Orchestrator: Run tasks through an AI coding agent with hook-driven chaining.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Manual mode — run pre-created task files
  python orchestrator.py ~/projects/my-app

  # GPT mode — GPT generates and manages tasks
  python orchestrator.py ~/projects/my-app --gpt -d "Build a todo app with auth"

  # Resume after interruption
  python orchestrator.py ~/projects/my-app --resume
        """,
    )

    parser.add_argument("project_dir", help="Path to the target project directory")

    # GPT mode
    parser.add_argument("--gpt", action="store_true", help="Enable GPT orchestration mode")
    parser.add_argument("-d", "--description", help="Project description (required with --gpt)")
    parser.add_argument("--gpt-model", default="gpt-5.2", help="GPT model (default: gpt-5.2)")
    parser.add_argument("--max-batches", type=int, default=5, help="Max GPT planning rounds (default: 5)")
    parser.add_argument("--batch-size", type=int, default=5, help="Tasks per batch (default: 5)")

    # Agent options
    parser.add_argument("--agent-model", default="sonnet", help="AI agent model (default: sonnet)")
    parser.add_argument("--max-cost-usd", type=float, default=50.0, help="Cost ceiling in USD (default: 50.0)")
    parser.add_argument("--task-timeout", type=int, default=600, help="Max seconds per task (default: 600)")

    # Other
    parser.add_argument("--resume", action="store_true", help="Resume from existing state")
    parser.add_argument("--verbose", action="store_true", help="Detailed logging")
    parser.add_argument("--openai-api-key", help="OpenAI API key (or use OPENAI_API_KEY env)")

    return parser.parse_args()


# ──────────────────────────────────────────────
# CLAUDE.md management
# ──────────────────────────────────────────────


class ContextMDManager:
    """Manages the context file (CLAUDE.md) in the target project directory."""

    def __init__(self, project_dir: Path):
        self.context_md = project_dir / "CLAUDE.md"
        self.backup_path = project_dir / ".claude" / "CLAUDE.md.orchestrator_backup"
        self.original_existed = self.context_md.exists()

    def backup(self):
        """Back up existing context file before orchestration."""
        if self.original_existed:
            self.backup_path.parent.mkdir(parents=True, exist_ok=True)
            self.backup_path.write_text(self.context_md.read_text())
            print(f"  Backed up existing context file")

    def restore(self):
        """Restore original context file after orchestration."""
        if self.backup_path.exists():
            self.context_md.write_text(self.backup_path.read_text())
            self.backup_path.unlink()
            print(f"  Restored original CLAUDE.md")
        elif not self.original_existed and self.context_md.exists():
            self.context_md.unlink()
            print(f"  Removed orchestrator CLAUDE.md")

    def write_initial(self, description: str = "", cumulative_summary: str = ""):
        """Write initial CLAUDE.md for the first task."""
        lines = [
            "# Orchestrator Context",
            "",
            "You are executing a task as part of an automated pipeline.",
            "Complete the task in your prompt thoroughly and precisely.",
            "Do not ask clarifying questions — make reasonable assumptions.",
            "Focus on writing working code.",
            "",
        ]

        if description:
            lines.extend([
                "## Project Description",
                description,
                "",
            ])

        lines.extend([
            "## Progress So Far",
            "(No tasks completed yet)",
            "",
        ])

        if cumulative_summary:
            lines.extend([
                "## Cumulative Summary",
                cumulative_summary,
                "",
            ])

        # Preserve original content
        if self.backup_path.exists():
            lines.extend([
                "---",
                "## Original Project Instructions",
                self.backup_path.read_text(),
            ])

        self.context_md.write_text("\n".join(lines))

    def rewrite_with_summary(self, description: str, cumulative_summary: str):
        """Rewrite CLAUDE.md with updated cumulative summary (between batches)."""
        self.write_initial(description=description, cumulative_summary=cumulative_summary)


# ──────────────────────────────────────────────
# Hook installation
# ──────────────────────────────────────────────


def install_hook(project_dir: Path):
    """Install the SessionEnd hook into the project's settings.local.json."""
    config_dir = project_dir / ".claude"
    config_dir.mkdir(exist_ok=True)

    settings_path = config_dir / "settings.local.json"
    hook_handler = str(ORCHESTRATOR_DIR / "hook_handler.py")

    # Read existing settings if present
    existing = {}
    if settings_path.exists():
        try:
            existing = json.loads(settings_path.read_text())
        except json.JSONDecodeError:
            existing = {}

    # Merge permissions
    permissions = existing.get("permissions", {})
    allow = set(permissions.get("allow", []))
    allow.update(["Bash", "Read", "Write", "Edit", "Glob", "Grep"])
    permissions["allow"] = sorted(allow)

    # Merge hook (preserve existing hooks for other events)
    existing["permissions"] = permissions
    hooks = existing.get("hooks", {})
    hooks["SessionEnd"] = [
        {
            "hooks": [
                {
                    "type": "command",
                    "command": hook_handler,
                    "timeout": 30,
                }
            ]
        }
    ]
    existing["hooks"] = hooks

    settings_path.write_text(json.dumps(existing, indent=2))
    print(f"  Installed SessionEnd hook → {hook_handler}")

    # Write reference file so hook_handler can find state.json
    ref_path = config_dir / "orchestrator_ref.json"
    ref_path.write_text(
        json.dumps(
            {
                "state_file": str(ORCHESTRATOR_DIR / "state.json"),
                "orchestrator_dir": str(ORCHESTRATOR_DIR),
            },
            indent=2,
        )
    )


def uninstall_hook(project_dir: Path):
    """Remove the orchestrator hook from settings.local.json."""
    settings_path = project_dir / ".claude" / "settings.local.json"
    ref_path = project_dir / ".claude" / "orchestrator_ref.json"

    if settings_path.exists():
        try:
            settings = json.loads(settings_path.read_text())
            settings.pop("hooks", None)
            settings_path.write_text(json.dumps(settings, indent=2))
            print(f"  Removed hook from settings.local.json")
        except json.JSONDecodeError:
            pass

    if ref_path.exists():
        ref_path.unlink()


# ──────────────────────────────────────────────
# Task discovery
# ──────────────────────────────────────────────


def discover_manual_tasks() -> list[dict]:
    """Discover task files in the tasks/ directory, sorted numerically."""
    tasks_dir = ORCHESTRATOR_DIR / "tasks"
    if not tasks_dir.exists():
        return []

    task_files = []
    for f in tasks_dir.iterdir():
        if f.suffix == ".md" and f.stem.isdigit():
            task_files.append((int(f.stem), f))

    # Sort by number
    task_files.sort(key=lambda x: x[0])

    tasks = []
    for num, filepath in task_files:
        content = filepath.read_text().strip()
        # Extract title from first heading or filename
        title = f"Task {num}"
        for line in content.split("\n"):
            line = line.strip()
            if line.startswith("# "):
                title = line[2:].strip()
                break

        tasks.append({
            "title": title,
            "file": f"tasks/{filepath.name}",
        })

    return tasks


# ──────────────────────────────────────────────
# Agent process management
# ──────────────────────────────────────────────


def launch_agent_task(project_dir: str, task_file: str, config: dict):
    """Launch an AI agent process for a task."""
    task_path = ORCHESTRATOR_DIR / task_file
    if not task_path.exists():
        print(f"  ERROR: Task file not found: {task_path}")
        return None

    prompt = task_path.read_text().strip()
    if not prompt:
        print(f"  ERROR: Task file is empty: {task_path}")
        return None

    cmd = [
        "claude",
        "-p",
        prompt,
        "--output-format",
        "json",
    ]

    agent_model = config.get("agent_model")
    if agent_model:
        cmd.extend(["--model", agent_model])

    proc = subprocess.Popen(
        cmd,
        cwd=project_dir,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )

    return proc


# ──────────────────────────────────────────────
# Main orchestration loop
# ──────────────────────────────────────────────


class Orchestrator:
    def __init__(self, args):
        self.args = args
        self.project_dir = Path(args.project_dir).resolve()
        self.state_path = str(ORCHESTRATOR_DIR / "state.json")
        self.state = State(self.state_path)
        self.context_md = ContextMDManager(self.project_dir)
        self.gpt = None
        self.shutting_down = False

        # Set up signal handler for graceful shutdown
        signal.signal(signal.SIGINT, self._handle_shutdown)
        signal.signal(signal.SIGTERM, self._handle_shutdown)

    def _handle_shutdown(self, signum, frame):
        """Graceful shutdown: set flag, let the polling loop handle cleanup.

        Avoids file I/O in signal handler to prevent deadlocks if signal
        arrives while a file lock is held.
        """
        if self.shutting_down:
            # Second interrupt — force exit
            print("\nForce quitting...")
            sys.exit(1)

        self.shutting_down = True
        print("\n\nShutting down gracefully...")
        print("  (Current task will finish but no new tasks will start)")

    def validate(self):
        """Validate prerequisites."""
        if not self.project_dir.is_dir():
            print(f"Error: Project directory not found: {self.project_dir}")
            sys.exit(1)

        # Check agent CLI
        try:
            result = subprocess.run(
                ["claude", "--version"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode != 0:
                print("Error: AI agent CLI not found or not working")
                sys.exit(1)
        except (FileNotFoundError, subprocess.TimeoutExpired):
            print("Error: AI agent CLI not found. Install it first.")
            sys.exit(1)

        if self.args.gpt:
            if not self.args.description:
                print("Error: --description is required with --gpt mode")
                sys.exit(1)

            api_key = self.args.openai_api_key or os.environ.get("OPENAI_API_KEY")
            if not api_key:
                print("Error: OpenAI API key not found. Set OPENAI_API_KEY or use --openai-api-key")
                sys.exit(1)

            lazy_import_gpt()
            self.gpt = GPTPlanner(api_key=api_key, model=self.args.gpt_model)

    def run(self):
        """Main orchestration loop."""
        self.validate()
        print(f"\n{'='*60}")
        print(f"  GPT Agent Orchestrator")
        print(f"{'='*60}")
        print(f"  Project:  {self.project_dir}")
        print(f"  Mode:     {'GPT' if self.args.gpt else 'Manual'}")
        print(f"  Agent:    {self.args.agent_model}")
        if self.args.gpt:
            print(f"  GPT:      {self.args.gpt_model}")
            print(f"  Batches:  {self.args.max_batches} x {self.args.batch_size} tasks")
        print(f"  Cost cap: ${self.args.max_cost_usd:.2f}")
        print(f"{'='*60}\n")

        if self.args.resume:
            self._resume()
        elif self.args.gpt:
            self._run_gpt_mode()
        else:
            self._run_manual_mode()

    def _run_manual_mode(self):
        """Run tasks from tasks/ directory."""
        tasks = discover_manual_tasks()
        if not tasks:
            print("No task files found in tasks/ directory.")
            print("Create numbered markdown files: tasks/1.md, tasks/2.md, ...")
            sys.exit(1)

        print(f"Found {len(tasks)} task(s):")
        for t in tasks:
            print(f"  • {t['file']}: {t['title']}")
        print()

        config = {
            "agent_model": self.args.agent_model,
            "max_cost_usd": self.args.max_cost_usd,
            "task_timeout": self.args.task_timeout,
        }

        # Initialize state
        State.create_initial(
            path=self.state_path,
            project_dir=str(self.project_dir),
            orchestrator_dir=str(ORCHESTRATOR_DIR),
            tasks=tasks,
            config=config,
            mode="manual",
        )

        # Set up project
        self.context_md.backup()
        self.context_md.write_initial()
        install_hook(self.project_dir)

        # Mark first task as running
        self.state.update_task(0, {"status": "running"})

        # Launch first task
        first_task = tasks[0]
        print(f"> Starting task 1/{len(tasks)}: {first_task['title']}")
        launch_agent_task(str(self.project_dir), first_task["file"], config)

        # Poll until done
        self._poll_until_complete()

        # Cleanup
        self._cleanup()

    def _run_gpt_mode(self):
        """Run with GPT generating batches of tasks."""
        description = self.args.description

        # Read description from file if it's a path
        if os.path.isfile(description):
            description = Path(description).read_text().strip()

        config = {
            "agent_model": self.args.agent_model,
            "max_cost_usd": self.args.max_cost_usd,
            "task_timeout": self.args.task_timeout,
            "gpt_model": self.args.gpt_model,
        }

        self.context_md.backup()
        install_hook(self.project_dir)

        cumulative_summary = ""
        previous_results = []
        total_task_index = 0

        for batch_num in range(1, self.args.max_batches + 1):
            if self.shutting_down:
                break

            print(f"\n{'─'*50}")
            print(f"  Batch {batch_num}/{self.args.max_batches}")
            print(f"{'─'*50}")

            # Ask GPT to plan tasks
            print(f"  Asking GPT to plan batch {batch_num}...")
            gpt_tasks = self.gpt.plan_batch(
                description=description,
                batch_num=batch_num,
                max_batches=self.args.max_batches,
                batch_size=self.args.batch_size,
                previous_results=previous_results,
                cumulative_summary=cumulative_summary,
            )

            if not gpt_tasks:
                print("  GPT says project is complete!")
                break

            # Write tasks to files
            task_entries = self.gpt.write_tasks_to_files(
                gpt_tasks, str(ORCHESTRATOR_DIR), start_index=total_task_index
            )

            print(f"  Generated {len(task_entries)} tasks:")
            for t in task_entries:
                print(f"    • {t['title']}")

            # Create or update state
            if batch_num == 1:
                State.create_initial(
                    path=self.state_path,
                    project_dir=str(self.project_dir),
                    orchestrator_dir=str(ORCHESTRATOR_DIR),
                    tasks=task_entries,
                    config=config,
                    mode="gpt",
                )
            else:
                # Add new batch tasks to existing state
                state_data = self.state.read()
                new_indices = []
                for t in task_entries:
                    idx = len(state_data["tasks"])
                    new_indices.append(idx)
                    state_data["tasks"].append({
                        "index": idx,
                        "title": t["title"],
                        "file": t["file"],
                        "status": "pending",
                        "session_id": None,
                        "transcript_path": None,
                        "result_summary": None,
                        "files_modified": [],
                        "cost_usd": 0,
                    })
                state_data["current_batch"] = batch_num
                state_data["current_task_index"] = new_indices[0]
                state_data["batches"][str(batch_num)] = {
                    "task_indices": new_indices,
                    "status": "running",
                }
                self.state.write(state_data)

            # Update CLAUDE.md
            self.context_md.rewrite_with_summary(description, cumulative_summary)

            # Mark first task of batch as running
            state_data = self.state.read()
            first_idx = state_data["current_task_index"]
            self.state.update_task(first_idx, {"status": "running"})

            # Launch first task
            first_task = task_entries[0]
            print(f"\n  > Starting: {first_task['title']}")
            launch_agent_task(str(self.project_dir), first_task["file"], config)

            # Poll until batch complete
            self._poll_until_batch_complete(batch_num)

            if self.shutting_down:
                break

            # Gather batch results for GPT assessment
            state_data = self.state.read()
            batch_info = state_data["batches"][str(batch_num)]
            batch_results = []
            for idx in batch_info["task_indices"]:
                task = state_data["tasks"][idx]
                batch_results.append({
                    "title": task["title"],
                    "success": task["status"] == "completed",
                    "result_summary": task.get("result_summary", ""),
                    "files_modified": task.get("files_modified", []),
                    "errors": [],
                })

            # GPT assessment
            print(f"\n  Asking GPT to assess batch {batch_num}...")
            assessment = self.gpt.assess_batch(
                description=description,
                batch_num=batch_num,
                batch_results=batch_results,
                previous_summary=cumulative_summary,
            )

            cumulative_summary = assessment.get("cumulative_summary", cumulative_summary)
            previous_results = batch_results
            total_task_index += len(task_entries)

            complete_pct = assessment.get("completion_percentage", 0)
            print(f"  Assessment: {complete_pct}% complete")
            if assessment.get("issues"):
                for issue in assessment["issues"]:
                    print(f"    WARNING: {issue}")

            if assessment.get("project_complete"):
                print(f"\n  GPT says project is complete!")
                break

            # Check cost
            if state_data.get("total_cost_usd", 0) >= self.args.max_cost_usd:
                print(f"\n  Cost ceiling reached: ${state_data['total_cost_usd']:.2f}")
                break

        self._cleanup()

    def _resume(self):
        """Resume from existing state file."""
        if not self.state.exists():
            print("No state file found. Nothing to resume.")
            sys.exit(1)

        state_data = self.state.read()
        print(f"Resuming from state: {state_data.get('status')}")
        print(f"  Tasks: {len(state_data.get('tasks', []))}")
        print(f"  Cost so far: ${state_data.get('total_cost_usd', 0):.2f}")

        # Find next pending task
        tasks = state_data.get("tasks", [])
        next_idx = None
        for i, t in enumerate(tasks):
            if t["status"] in ("pending", "running"):
                next_idx = i
                break

        if next_idx is None:
            print("All tasks already completed.")
            self._cleanup()
            return

        # Re-install hook
        self.project_dir = Path(state_data["project_dir"])
        self.context_md = ContextMDManager(self.project_dir)
        install_hook(self.project_dir)

        # Reset status and persist current_task_index
        state_data["status"] = "running"
        state_data["current_task_index"] = next_idx
        self.state.write(state_data)
        self.state.update_task(next_idx, {"status": "running"})

        task = tasks[next_idx]
        print(f"\n  > Resuming task {next_idx + 1}/{len(tasks)}: {task['title']}")
        launch_agent_task(
            str(self.project_dir),
            task["file"],
            state_data.get("config", {}),
        )

        self._poll_until_complete()
        self._cleanup()

    def _poll_until_complete(self, poll_interval: float = 3.0):
        """Poll state.json until all tasks are done or aborted."""
        last_index = -1

        while True:
            if self.shutting_down:
                # Signal handler set the flag — do the I/O cleanup here (safe)
                try:
                    if self.state.exists():
                        self.state.set_status("aborted", "User interrupted")
                except Exception:
                    pass
                break

            time.sleep(poll_interval)

            try:
                state_data = self.state.read()
            except (json.JSONDecodeError, OSError):
                continue

            status = state_data.get("status", "")
            if status in ("completed", "aborted"):
                break

            current_idx = state_data.get("current_task_index", 0)
            tasks = state_data.get("tasks", [])
            total = len(tasks)

            # Print progress
            if current_idx != last_index:
                completed = sum(1 for t in tasks if t["status"] in ("completed", "failed"))
                running = sum(1 for t in tasks if t["status"] == "running")
                cost = state_data.get("total_cost_usd", 0)

                if running > 0:
                    running_task = next(
                        (t for t in tasks if t["status"] == "running"), None
                    )
                    name = running_task["title"] if running_task else "?"
                    print(f"  [{completed}/{total}] Running: {name} (${cost:.2f} spent)")

                last_index = current_idx

            # Check if all done
            all_done = all(t["status"] in ("completed", "failed") for t in tasks)
            if all_done:
                break

            # Stall detection
            for t in tasks:
                if t["status"] == "running" and t.get("started_at"):
                    try:
                        started = datetime.fromisoformat(t["started_at"])
                        elapsed = (
                            datetime.now(timezone.utc) - started
                        ).total_seconds()
                        if elapsed > self.args.task_timeout:
                            print(f"  WARNING: Task {t['index']+1} stalled ({elapsed:.0f}s)")
                            self.state.update_task(
                                t["index"],
                                {"status": "failed", "result_summary": "Timeout / stall detected"},
                            )
                    except (ValueError, TypeError):
                        pass

    def _poll_until_batch_complete(self, batch_num: int, poll_interval: float = 3.0):
        """Poll until a specific batch is done."""
        last_index = -1

        while True:
            if self.shutting_down:
                try:
                    if self.state.exists():
                        self.state.set_status("aborted", "User interrupted")
                except Exception:
                    pass
                break

            time.sleep(poll_interval)

            try:
                state_data = self.state.read()
            except (json.JSONDecodeError, OSError):
                continue

            status = state_data.get("status", "")
            if status in ("aborted",):
                break

            batch = state_data.get("batches", {}).get(str(batch_num), {})
            if batch.get("status") == "completed":
                break

            # Print progress
            current_idx = state_data.get("current_task_index", 0)
            if current_idx != last_index:
                batch_indices = batch.get("task_indices", [])
                tasks = state_data.get("tasks", [])
                completed = sum(
                    1
                    for i in batch_indices
                    if i < len(tasks) and tasks[i]["status"] in ("completed", "failed")
                )
                total = len(batch_indices)
                cost = state_data.get("total_cost_usd", 0)

                running_task = next(
                    (tasks[i] for i in batch_indices if i < len(tasks) and tasks[i]["status"] == "running"),
                    None,
                )
                if running_task:
                    print(f"  [{completed}/{total}] Running: {running_task['title']} (${cost:.2f} spent)")

                last_index = current_idx

            # Check if all batch tasks done
            batch_indices = batch.get("task_indices", [])
            tasks = state_data.get("tasks", [])
            all_done = all(
                tasks[i]["status"] in ("completed", "failed")
                for i in batch_indices
                if i < len(tasks)
            )
            if all_done:
                break

    def _cleanup(self):
        """Clean up after orchestration."""
        print(f"\n{'='*60}")

        if self.state.exists():
            state_data = self.state.read()
            tasks = state_data.get("tasks", [])
            completed = sum(1 for t in tasks if t["status"] == "completed")
            failed = sum(1 for t in tasks if t["status"] == "failed")
            cost = state_data.get("total_cost_usd", 0)

            print(f"  Results:")
            print(f"    Completed: {completed}/{len(tasks)} tasks")
            if failed:
                print(f"    Failed:    {failed} tasks")
            print(f"    Cost:      ${cost:.2f}")
            print()

            # Print per-task summary
            for t in tasks:
                icon = "[+]" if t["status"] == "completed" else "[x]" if t["status"] == "failed" else "[ ]"
                print(f"    {icon} {t['title']}")
                if t.get("files_modified"):
                    print(f"      Files: {', '.join(t['files_modified'][:5])}")

            if state_data.get("status") != "aborted":
                state_data["status"] = "completed"
                self.state.write(state_data)

        # Restore project
        try:
            self.context_md.restore()
        except Exception:
            pass

        try:
            uninstall_hook(self.project_dir)
        except Exception:
            pass

        print(f"\n{'='*60}")
        print(f"  Done. State saved to: {self.state_path}")
        print(f"{'='*60}\n")


# ──────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────

if __name__ == "__main__":
    args = parse_args()
    orchestrator = Orchestrator(args)
    orchestrator.run()
